test:
  service: RecordDisk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: RecordDisk
  root: <%= Rails.root.join("storage") %>

cloud:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV.fetch("AWS_REGION", "us-east-1") %>
  bucket: <%= ENV["AWS_BUCKET"] %>
  endpoint: <%= ENV["AWS_ENDPOINT"] %>
  force_path_style: <%= ENV.fetch("AWS_FORCE_PATH_STYLE", "false") == "true" %>
